### ISSUE TITLE
prefix doesn't work

### ISSUE THREAD

**Issue by phanhiep579x** [Uo1428/ALL-IN-ONE-Discord-Bot-#26]
![bug](https://github.com/Uo1428/ALL-IN-ONE-Discord-Bot-/assets/61640819/3dbe4a7d-01ce-4e05-8d7e-c8f059ead850)

Command doesn't work with prefix, only slash command seems to function :-? Any ideas what is going on? Much appreciated

**Comment by hotsu0p** [comment]
does it have the message intent enabled?

**Comment by Uo1428** [comment]
prefix is only for custom commands.
